# Generated by Django 5.1.4 on 2025-02-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelogs',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='dscmaster',
            name='type',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Individual', 'Individual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usagelogs',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usr'),
        ),
    ]
