# Generated by Django 5.1.4 on 2025-02-15 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usagelogs_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='action_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inout',
            name='action_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inout',
            name='initiated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inout',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='agent_mob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='direction',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='inout',
            name='initiation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
