# Generated by Django 5.1.4 on 2025-02-15 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_inout_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='initiated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
