# Generated by Django 5.1.4 on 2025-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_inout_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='initiation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
