# Generated by Django 5.1.4 on 2025-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_inout_initiation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='direction',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=10),
        ),
    ]
