# Generated by Django 5.1.4 on 2025-02-28 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_dscmaster_dsc_class_alter_dscmaster_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscmaster',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usr',
        ),
    ]
