# Generated by Django 5.1.4 on 2025-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dscmaster_user_id_delete_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSCExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=50)),
            ],
        ),
    ]
