# Generated by Django 5.1.4 on 2025-03-16 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_dscextrafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscextrafield',
            name='dsc_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dscextrafield',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dscextrafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=20),
        ),
        migrations.CreateModel(
            name='DSCExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('dsc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dscmaster')),
            ],
        ),
    ]
