# Generated by Django 5.1.4 on 2025-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_dscextrafield_dsc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscmaster',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
