# Generated by Django 5.1.4 on 2025-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_dscmaster_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscextrafield',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dscextrafield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dscextrafield',
            name='dsc_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dscextrafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20),
        ),
    ]
