# Generated by Django 5.1.4 on 2025-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_dscextrafield_label_dscextrafield_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscextrafield',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
