# Generated by Django 5.1.4 on 2025-03-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_dscextrafield_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dscextrafield',
            name='help_text',
        ),
    ]
