# Generated by Django 5.1.4 on 2025-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_dscextrafield_help_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dscextradata',
            unique_together={('dsc_number', 'field_name')},
        ),
    ]
