# Generated by Django 5.1.4 on 2025-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_dscextradata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscextrafield',
            name='field_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
