# Generated by Django 5.1.4 on 2025-04-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_create_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelogs',
            name='form_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.forms'),
        ),
        migrations.AlterField(
            model_name='usagelogs',
            name='platform_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.platform'),
        ),
    ]
