# Generated by Django 5.1.6 on 2025-04-30 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_dscmaster_generated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dscrenewal',
            name='shelf_no',
        ),
        migrations.CreateModel(
            name='ShelfAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('assign', 'Assign'), ('unassign', 'Unassign')], max_length=10)),
                ('remarks', models.TextField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dsc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dscmaster')),
                ('shelf_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shelf')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
    ]
