# Generated by Django 5.1.6 on 2025-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_dscrenewal_shelf_no_shelfassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
