# Generated by Django 5.1.6 on 2025-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_shelfassignment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('help_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dscrenewal',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
