# Generated by Django 5.1.6 on 2025-05-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_renewalextrafield_dscrenewal_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSCRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateTimeField(auto_now_add=True)),
                ('previous_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('documents_snapshot', models.JSONField(blank=True, null=True)),
                ('dsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='home.dscmaster')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DSC Renewal Histories',
                'ordering': ['-renewal_date'],
            },
        ),
    ]
