# Generated by Django 5.1.6 on 2025-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_dscrenewalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dscrenewalhistory',
            name='documents_snapshot',
        ),
        migrations.AddField(
            model_name='dscrenewalhistory',
            name='document_changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dscrenewalhistory',
            name='new_documents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dscrenewalhistory',
            name='previous_documents',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dscrenewalhistory',
            name='new_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dscrenewalhistory',
            name='previous_data',
            field=models.JSONField(default=dict),
        ),
    ]
