# Generated by Django 5.1.6 on 2025-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_dscrenewalhistory_documents_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
